backend:
  name: github
  repo: thudm309/vibeagency
  branch: main
  base_url: https://vibeagency.vn
  auth_endpoint: api/auth
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
