name: Auto Deploy Blog Content

on:
  push:
    branches: [ main ]
    paths:
      - 'content/blog/**'
      - 'public/uploads/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: vibeagency
          directory: ./
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
